// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGmYNlVtOICOkjTEEROKk78wfRcDaKnVk',
    appId: '1:1032790144017:android:0489d25f4275f583622db0',
    messagingSenderId: '1032790144017',
    projectId: 'learnwayv2',
    storageBucket: 'learnwayv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCss5SUggAZOLmiEy384LMa4aq67fiBXIk',
    appId: '1:1032790144017:ios:60a8b270cc8205b0622db0',
    messagingSenderId: '1032790144017',
    projectId: 'learnwayv2',
    storageBucket: 'learnwayv2.firebasestorage.app',
    androidClientId: '1032790144017-4eb84rgqvcrk0c06dkvs5apto1bncvs8.apps.googleusercontent.com',
    iosClientId: '1032790144017-3dts7s7hc7fvv7a3eqvme70393pen4ao.apps.googleusercontent.com',
    iosBundleId: 'xyz.learnway.app',
  );

}